import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Suspense } from "react";
import Marquee from "@/Components/Marquee";

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className}    h-full antialiased scroll-smooth
      data-scroll-behavior="smooth`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div className="h-24" />}>
          <Navbar />
          <Marquee />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
